### ISSUE TITLE
No minimal size and window position restoration

### ISSUE THREAD

**Issue by PeterPanino** [sindresorhus/Pasteboard-Viewer#11]
This app is ALMOST what I need - except it has a minimal window size of 500*352 pixels. I need the window size to become SMALLER!
Also, the window position is not restored after a restart. The last window position should be automatically restored after a restart!

**Comment by sindresorhus** [comment]
> Also, the window position is not restored after a restart. The last window position should be automatically restored after a restart!

I cannot reproduce this. Make sure you are on macOS 12.1 and Pasteboard Viewer 2.2.1 or later.
