### ISSUE TITLE
Don't resize small pixel graphics

### ISSUE THREAD

**Issue by PeterPanino** [sindresorhus/Pasteboard-Viewer#12]
When I copy a graphic to the clipboard, then Pasteboard Viewer always fits the graphic to its window size. This leads to ugly effects with small pixel graphics. So there should be an option to keep the pixel graphic at its original size if it is smaller than the window client size.

**Comment by sindresorhus** [comment]
This is a bug. It should only scale down, not up. I'll get this and your other issue fixed after Xmas vacation (in a couple of weeks).

**Comment by sindresorhus** [comment]
There's an update in the App Store now with these changes.
