### ISSUE TITLE
Decode “dyn.” types

### ISSUE THREAD

**Issue by avidrissman** [sindresorhus/Pasteboard-Viewer#18]
As a developers, we sometimes need our tools to go a bit beyond and a bit undocumented :) Sometimes, when I use Pasteboard Viewer, it lists “dyn.” flavors. These are not useful to me. They result from code using non-uniform-type types, and it would be helpful to know what they really mean behind the scenes.

The encoding of “dyn.” types is well-known. See https://alastairs-place.net/blog/2012/06/06/utis-are-better-than-you-think-and-heres-why/ and code at https://gist.github.com/jtbandes/19646e7457208ae9b1ad.

Can you extend Pasteboard Viewer to decode and display the decoded meaning of “dyn.” flavors?

Thanks!

**Comment by sindresorhus** [comment]
Good idea. Will do.

How do you think it should be presented?

**Comment by avidrissman** [comment]
Lots of options here.

Maybe if it’s only a PboardType then substitute that in, perhaps with parens? Maybe keep the “dyn” name but put an (i) on the right with a popup with the breakout into a dictionary? I’m not super familiar with the options available in Swift, so I would totally leave it to you.

**Comment by avidrissman** [comment]
Actually, now that I think about it, the structure of UTIs is clear, so if a dyn UTI decoded to a PboardType, you could probably just substitute that in, since PboardTypes are going to be the most likely cause of a dyn UTI. MIME types are also very noticeable, so unwrapping in general might be a workable solution.

**Comment by sindresorhus** [comment]
I have implemented this now. The real type name will show up as a subtitle in the sidebar and as the header in the preview screen. Can you try it out and let me know how it works for you? Requires macOS 13.1

[Pasteboard Viewer.app.zip](https://github.com/sindresorhus/Pasteboard-Viewer/files/10472636/Pasteboard.Viewer.app.zip)

**Comment by avidrissman** [comment]
I’ve played with this build and seeing the PBoard equivalents is fantastic. Thank you so much! Hope to see it in the App Store soon for everyone.

**Comment by avidrissman** [comment]
The only thing that might make it better is, in the context menu for the sidebar item, add a “Copy Pasteboard Type” menu below the “Copy Type Identifier” menu item so that you can easily copy the PboardType string.

**Comment by sindresorhus** [comment]
The update is out in the App Store.
