### ISSUE TITLE
Add a way to reduce the pasteboard to just the selected type

### ISSUE THREAD

**Issue by j-f1** [sindresorhus/Pasteboard-Viewer#19]
Sometimes I want to strip out e.g. the styling information from some text I’ve copied in Safari. It would be nice if I could hit ⌘C to delete everything from the pasteboard except the currently selected thing in the sidebar (assuming, of course, that there’s nothing selected in the detail view)

**Comment by sindresorhus** [comment]
Sounds like you want [Pure Paste](https://sindresorhus.com/pure-paste), not this app.

**Comment by j-f1** [comment]
Not necessarily! I think some of the cases I remember were along the lines of copying a link containing an image and wanting to either paste just the image or just the URL, or wanting to just copy the file URL of an item in Finder.

**Comment by sindresorhus** [comment]
That is outside the scope of this app. This app is a tool to aid making Mac apps, not a general clipboard utility app. I'll keep this in mind when I eventually make a clipboard manager/utility app.
