### ISSUE TITLE
App doesn't show the correct source.

### ISSUE THREAD

**Issue by Fishel-The-Genius** [sindresorhus/Pasteboard-Viewer#20]
I'm using 'grid' window manager, to manage tiling windows to left or right etc. 
Whenever I'm copying from Spotlight or Raycast it shows the right source, But when I'm copying from any other app that has a regular window, then the app shows that the source is 'Grid'.

**Comment by sindresorhus** [comment]
This app https://macgrid.app? I just tried it and I'm unable to reproduce the issue.

What Pasteboard Viewer version are you on?
