### ISSUE TITLE
Can't copy browser custom data

### ISSUE THREAD

**Issue by foxt** [sindresorhus/Pasteboard-Viewer#21]
If I copy data ffrom a browser that has custom data attached to it, such as from Google Docs, the viewer becomes disabled and you cannot text select
![image](https://github.com/sindresorhus/Pasteboard-Viewer/assets/12257112/51c6fe3e-d666-4e9d-8f8b-6dcff674c4a0)

**Comment by sindresorhus** [comment]
If the app doesn't recognize the type, it uses Quick Look to render the preview and Quick Look does not support text selection. The specific format cannot be decoded as a string normally.
