### ISSUE TITLE
Hex screen

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/Pasteboard-Viewer#24]
![ZVVlbqEHxEgX1692950168127](https://github.com/sindresorhus/Pasteboard-Viewer/assets/170270/899bfd6a-c4b9-4193-bd06-dcbc0bc97524)

**Comment by davedelong** [comment]
I'm interested in tackling this, and the natural way to do this seems to use the [HexFiend framework](https://github.com/HexFiend/HexFiend).
