### ISSUE TITLE
If strings are encoded as UTF-16, they are interpreted, whereas they’re not if encoded as UTF-8

### ISSUE THREAD

**Issue by avidrissman** [sindresorhus/Pasteboard-Viewer#29]
Pasteboard Viewer is a useful tool to show exactly what’s on the pasteboard, so it should show it in the lowest-level format. However, when strings are encoded as UTF-16 they are interpreted.

For example, compile and run:

```Objective-C
// save as pasteboard8.m, compile with
// cc pasteboard8.m -o pasteboard8 -framework AppKit

#import <AppKit/AppKit.h>

int main() {
  NSPasteboard* pb = NSPasteboard.generalPasteboard;
  [pb clearContents];
  
  [pb setData:[@"<html><p>hi</html>" dataUsingEncoding:NSUTF8StringEncoding] forType:NSPasteboardTypeHTML];
}
```

If you run that, and then use Pasteboard Viewer, you get:

<img width="818" alt="image" src="https://github.com/sindresorhus/Pasteboard-Viewer/assets/3914435/cd9badcc-027f-45da-b6eb-621dd290e311">

Perfect. Now compile and run:

```Objective-C
// save as pasteboard16.m, compile with
// cc pasteboard16.m -o pasteboard16 -framework AppKit

#import <AppKit/AppKit.h>

int main() {
  NSPasteboard* pb = NSPasteboard.generalPasteboard;
  [pb clearContents];
  
  // Loaded and displayed as the actual HTML contents:
  [pb setData:[@"<html><p>hi</html>" dataUsingEncoding:NSUTF16StringEncoding] forType:NSPasteboardTypeHTML];
}
```

If you run that, and then use Pasteboard Viewer, you get:

<img width="818" alt="image" src="https://github.com/sindresorhus/Pasteboard-Viewer/assets/3914435/08db8d79-4a5e-4ded-8f9a-a645aca84f53">

which interprets the data as HTML and loads the styled string.

It would be best if the raw string were shown, even if it is encoded other than UTF-8.

**Comment by sindresorhus** [comment]
Fixed in the latest update.
