### ISSUE TITLE
Feature Request: A toolbar item to keep the window always-on-top

### ISSUE THREAD

**Issue by francisfeng** [sindresorhus/Pasteboard-Viewer#9]
When I'm developing the copy or paste feature in my app, I need to monitor my Pasteboard's current content. 

So far I have to constantly switch windows to see what's in my Pasteboard.

It would be nice to have a toolbar item so that I can easily switch this behavior.

**Comment by sindresorhus** [comment]
This is already available in the the "Window" menu.
